name: Gradle publish

on:
  push:

  # trigger when starred
  watch:
    types: [started]  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: ./gradlew publish
      env:
        USERNAME: token
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
